### ISSUE TITLE
Возвращает false при успешном платеже со сберегательного счета

### ISSUE THREAD

**Issue by NatKobeleva** [Novadiss/JavaQA-Team-Diplom-2#13]
## Описание
При проведении операции оплаты со сберегательного счета возвращается результат false когда текущий баланс становится равен минимальному балансу

## Локация дефекта
https://github.com/Novadiss/JavaQA-Team-Diplom-2/blob/8d7719a6eeca0145a95466f1df3ccb4933c78020/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44
## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Novadiss/JavaQA-Team-Diplom-2/tree/saving) в IDEA
2. Перейти в класс SavingAccountTest
3. Установить в тесте shouldTrueIfPayToMinBalance параметры для переменной  account равные 8_000, 1_000, 10_000, 5
4. Выставить значение переменной для account.pay(7_000);
5. Запустить тест
6. Посмотреть на вывод в консоли

*Ожидаемый результат*: тест пройден успешно - вернулось true
*Фактический результат*: тест пройден с ошибкой - expected true, actual false

## Ссылка на тест
https://github.com/Novadiss/JavaQA-Team-Diplom-2/blob/8d7719a6eeca0145a95466f1df3ccb4933c78020/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L151-L160
## Окружение

- **Операционная система:** Windows 10
- **IDE:** IntelliJ IDEA 2023.2 Community Edition
- **Java:** OpenJDK 11

**Comment by Novadiss** [comment]
Код исправлен, тест проходит.
Функция выполняется согласно ТЗ.

**Comment by NatKobeleva** [comment]
## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Novadiss/JavaQA-Team-Diplom-2/tree/saving) в IDEA
2. Перейти в класс SavingAccountTest
3. Создать в тесте shouldTrueIfPayToMinBalance новый объект класса SavingAccount
4. Установить параметры для переменной account равные 8_000, 1_000, 10_000, 5
5. Вызвать метод account.pay и выставить значение переменной равное 7_000
6. Сравнить булевые значения, а именно ожидаемый результат после покупки на сумму 7000 с результатом после вызова метода pay
7. Запустить тест
8. Посмотреть на вывод в консоли

**Comment by NatKobeleva** [comment]
Отредактированы шаги воспроизведения
