### ISSUE TITLE
Баланс сберегательного счета не увеличивается на сумму пополнения до размеров максимального баланса

### ISSUE THREAD

**Issue by NatKobeleva** [Novadiss/JavaQA-Team-Diplom-2#15]
## Описание
При проведении операции пополнения сберегательного счета текущий баланс не увеличивается на сумму пополнения до размеров максимального  баланса

## Локация дефекта
https://github.com/Novadiss/JavaQA-Team-Diplom-2/blob/8d7719a6eeca0145a95466f1df3ccb4933c78020/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68
## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Novadiss/JavaQA-Team-Diplom-2/tree/saving) в IDEA
2. Перейти в класс SavingAccountTest
3. Установить в тесте shouldAddToMaxBalance параметры для переменной  account равные 2_000, 1_000, 10_000, 5
4. Выставить значение переменной для account.add(8_000)
5. Запустить тест
6. Посмотреть на вывод в консоли

*Ожидаемый результат*: тест пройден успешно - баланс увеличился на сумму пополнения и стал равен максимальному
*Фактический результат*: тест пройден с ошибкой - expected 10000, actual 2000

## Ссылка на тест
https://github.com/Novadiss/JavaQA-Team-Diplom-2/blob/8d7719a6eeca0145a95466f1df3ccb4933c78020/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L223-L232
## Окружение

- **Операционная система:** Windows 10
- **IDE:** IntelliJ IDEA 2023.2 Community Edition
- **Java:** OpenJDK 11

**Comment by Novadiss** [comment]
Код исправлен, тест проходит.
Функция выполняется согласно ТЗ.

**Comment by NatKobeleva** [comment]
## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Novadiss/JavaQA-Team-Diplom-2/tree/saving) в IDEA
2. Перейти в класс SavingAccountTest
3. Создать в тесте shouldAddToMaxBalance новый объект класса SavingAccount
4. Установить параметры для переменной account равные 2_000, 1_000, 10_000, 5
5. Вызвать метод account.add и выставить значение переменной равное 8_000
6. Сравнить ожидаемый баланс после пополнения счета на сумму 8000 и баланс после вызова метода add
7. Запустить тест
8. Посмотреть на вывод в консоли

**Comment by NatKobeleva** [comment]
Отредактированы шаги воспроизведения
