### ISSUE TITLE
Не настроено исключение при создании объекта сбер. счета когда минимальный баланс отрицательный

### ISSUE THREAD

**Issue by NatKobeleva** [Novadiss/JavaQA-Team-Diplom-2#20]
## Описание
При создании нового объекта сберегательного счета, когда минимальный баланс указывается как отрицательное число, метод не завершается с нужной ошибкой

## Локация дефекта
https://github.com/Novadiss/JavaQA-Team-Diplom-2/blob/f872bde308b8a3bf437e7ba93abce7e2b050f1bc/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L23
## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Novadiss/JavaQA-Team-Diplom-2/tree/saving) в IDEA
2. Перейти в класс SavingAccountTest
3. Установить в тесте shouldThrowExceptionIfMinBalanceNegative параметры для переменной account равные 1_000, -1_000, 15_000, 3
4. Запустить тест
5. Посмотреть на вывод в консоли
*Ожидаемый результат*: тест пройден успешно
*Фактический результат*: тест пройден с ошибкой, выброс исключения не произошел

## Ссылка на тест
https://github.com/Novadiss/JavaQA-Team-Diplom-2/blob/f872bde308b8a3bf437e7ba93abce7e2b050f1bc/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L67-L75
## Окружение

- **Операционная система:** Windows 10
- **IDE:** IntelliJ IDEA 2023.2 Community Edition
- **Java:** OpenJDK 11

**Comment by Novadiss** [comment]
Код исправлен, тест проходит.
Функция выполняется согласно ТЗ.

**Comment by NatKobeleva** [comment]
## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Novadiss/JavaQA-Team-Diplom-2/tree/saving) в IDEA
2. Перейти в класс SavingAccountTest
3. Создать в тесте shouldThrowExceptionIfMinBalanceNegative  новый объект класса SavingAccount
4. Установить в новом объекте для переменной account параметры равные 1_000, -1_000, 15_000, 3
5. Запустить тест
6. Посмотреть на вывод в консоли

Ожидаемый результат: тест пройден успешно - ожидаемая ошибка совпала с выбрасываемым исключением
Фактический результат: тест пройден с ошибкой, выброс исключения не произошел

**Comment by NatKobeleva** [comment]
Отредактированы шаги воспроизведения и ожидаемый результат
