### ISSUE TITLE
Проценты на остаток счета равны 0 когда текущий счет менее 100

### ISSUE THREAD

**Issue by NatKobeleva** [Novadiss/JavaQA-Team-Diplom-2#25]
## Описание
При расчете процентов на остаток счета когда текущий баланс менее 100 результат получается равным 0

## Локация дефекта
https://github.com/Novadiss/JavaQA-Team-Diplom-2/blob/51bb6c582ab77f6de5b418a6bb3028d6fc779370/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L113
## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Novadiss/JavaQA-Team-Diplom-2/tree/saving) в IDEA
2. Перейти в класс SavingAccountTest
3. Создать в тесте shouldYearChangeIfBalanceLess100 новый объект класса SavingAccount
4. Установить параметры для переменной account равные 80, 0,  10_000, 5
5. Положить в переменную int expected ожидаемый результат равный 4
6. Положить в переменную int actual метод account.yearChange()
7. Запустить тест
8. Посмотреть на вывод в консоли

*Ожидаемый результат*: тест пройден успешно - рассчитаны проценты на остаток счета 
*Фактический результат*: тест пройден с ошибкой - expected 4, actual 0

## Ссылка на тест
https://github.com/Novadiss/JavaQA-Team-Diplom-2/blob/51bb6c582ab77f6de5b418a6bb3028d6fc779370/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L370-L380
## Окружение

- **Операционная система:** Windows 10
- **IDE:** IntelliJ IDEA 2023.2 Community Edition
- **Java:** OpenJDK 11

**Comment by Novadiss** [comment]
Расчет годовых процентов откорректирован
Теперь баланс сначала умножается на ставку и только потом делится на 100
