### ISSUE TITLE
Не настроено исключение при создании объекта сбер. счета когда min баланс больше max баланса

### ISSUE THREAD

**Issue by NatKobeleva** [Novadiss/JavaQA-Team-Diplom-2#8]
## Описание
При создании нового объекта сберегательного счета, когда минимальный баланс указывается больше чем максимальный, метод не завершается с нужной ошибкой

## Локация дефекта
https://github.com/Novadiss/JavaQA-Team-Diplom-2/blob/8d7719a6eeca0145a95466f1df3ccb4933c78020/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22
## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Novadiss/JavaQA-Team-Diplom-2/tree/saving) в IDEA
2. Перейти в класс SavingAccountTest
3. Установить в тесте shouldThrowExceptionIfMinBalanceMoreMaxBalance параметры для переменной  account равные 5_000, 18_000, 15_000, 3
4. Запустить тест
5. Посмотреть на вывод в консоли

*Ожидаемый результат*: тест пройден успешно
*Фактический результат*: тест пройден с ошибкой, выброс исключения не произошел

## Ссылка на тест
https://github.com/Novadiss/JavaQA-Team-Diplom-2/blob/8d7719a6eeca0145a95466f1df3ccb4933c78020/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L34-L41
## Окружение

- **Операционная система:** Windows 10
- **IDE:** IntelliJ IDEA 2023.2 Community Edition
- **Java:** OpenJDK 11

**Comment by Novadiss** [comment]
Код исправлен, тест проходит.
Функция выполняется согласно ТЗ.

**Comment by NatKobeleva** [comment]
## Описание
При создании нового объекта сберегательного счета, когда минимальный баланс указывается больше чем максимальный, метод не завершается с нужной ошибкой

## Локация дефекта
https://github.com/Novadiss/JavaQA-Team-Diplom-2/blob/2e86453fdca0c83a881086c885f1778c5e0e43a3/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L23

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/Novadiss/JavaQA-Team-Diplom-2/tree/saving) в IDEA
2. Перейти в класс SavingAccountTest
3. Создать в тесте shouldThrowExceptionIfMinBalanceMoreMaxBalance новый объект класса SavingAccount
4. Установить в новом объекте для переменной account параметры равные 5_000, 18_000, 15_000, 3
5. Запустить тест
6. Посмотреть на вывод в консоли

Ожидаемый результат: тест пройден успешно - ожидаемая ошибка совпала с выбрасываемым исключением
Фактический результат: тест пройден с ошибкой, выброс исключения не произошел

## Ссылка на тест
https://github.com/Novadiss/JavaQA-Team-Diplom-2/blob/2e86453fdca0c83a881086c885f1778c5e0e43a3/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L34-L42
## Окружение

- **Операционная система:** Windows 10
- **IDE:** IntelliJ IDEA 2023.2 Community Edition
- **Java:** OpenJDK 11
